db_path: "../../jjajang/data/naver/research.db3"

# 신규 모델 설정 섹션, ollama local 모델은 websearch 기능에 사용한다.
models:
  qwen_local:
    provider: "ollama"
    name: "qwen3.5:latest"
    base_url: "http://192.168.0.10:11434"
    num_ctx: 131072  # 서버 상황에 따라 64K, 128K 동적으로 설정됨. 기본은 128K
  gpt_oss_local:
    provider: "ollama"
    name: "gpt-oss:latest"
    base_url: "http://192.168.0.10:11434"
    num_ctx: 131072
  qwen_coder_local:
    provider: "ollama"
    name: "qwen3-coder:latest"
    base_url: "http://192.168.0.10:11434"
    num_ctx: 131072
  qwen_cloud:
    provider: "ollama"
    name: "qwen3.5:cloud"
    base_url: "http://localhost:11434"
    num_ctx: 262144
  qwen_coder_next_cloud:
    provider: "ollama"
    name: "qwen3-coder-next:cloud"
    base_url: "http://localhost:11434"
    num_ctx: 262144
  minimax_cloud:
    provider: "ollama"
    name: "minimax-m2.7:cloud"
    base_url: "http://localhost:11434"
    num_ctx: 200000
  nemotron_cloud:
    provider: "ollama"
    name: "nemotron-3-super:cloud"
    base_url: "http://localhost:11434"
    num_ctx: 262144
  gpt_oss_cloud:
    provider: "ollama"
    name: "gpt-oss:120b-cloud"
    base_url: "http://localhost:11434"
    num_ctx: 131072
  # gpt_oss_free:
  #   provider: "openrouter"
  #   name: "openai/gpt-oss-120b:free"
  #   base_url: "https://openrouter.ai/api/v1"

query_limits:
  company: 5
  market_info: 5
  invest: 5
  default: 5

llm_config:
  temperature: 0.1
  max_length_market: 20000
  max_length_stock: 15000

  # 노드별 전용 모델 매핑 (models 섹션의 키를 참조), qwen_coder_next_cloud, nemotron_cloud
  # market_analysis_model: "qwen_cloud"      # 시장 트렌드 분석용
  # stock_analysis_model: "minimax_cloud"     # 종목 리포트 분석용
  # report_generation_model: "gpt_oss_cloud"  # 최종 투자 보고서 생성용
  market_analysis_model: "nemotron_cloud"      # 시장 트렌드 분석용
  stock_analysis_model: "nemotron_cloud"     # 종목 리포트 분석용
  report_generation_model: "nemotron_cloud"  # 최종 투자 보고서 생성용
